<?php
include_once("class/pages/StorePage.php");

include_once("beans/NewsItemsBean.php");
include_once("components/PublicationsComponent.php");


class NewsPageBase extends StorePage
{
    protected $news = null;
    protected $pac = null;

    public function __construct()
    {
        parent::__construct();

        $this->addCSS(STORE_LOCAL . "/css/news.css");

        $this->news = new NewsItemsBean();

        $this->pac = new PublicationsComponent($this->news, LOCAL . "/news/index.php");
    }

    public function getPublications() : PublicationsComponent
    {
        return $this->pac;
    }

    public function renderArchive()
    {
        echo "<div class='column other'>";

        $this->pac->render();

        echo "</div>"; //column_other
    }
    public function renderNewsList()
    {
        echo "<div class='column main'>";

        $arr = $this->pac->getSelection();
        if (count($arr)>0) {
            $qry = $this->pac->getBean()->query(...$this->pac->getSelectionColumns());
            $qry->select->where()->add($this->news->key(), "(" . implode(",", $arr) . ")", " IN ");
            $qry->exec();

            while ($item = $qry->next()) {
                echo "<div class='item'>";
                echo "<div class='title'>" . $item["item_title"] . "</div>";
                echo "<div class='date'>" . date($this->pac->getItemRenderer()->getDateFormat(), strtotime($item["item_date"])) . "</div>";

                echo "<div class='image'>";
                $img_href = StorageItem::Image($item[$qry->key()], $this->news);
                echo "<img width=100% src='$img_href'>";
                echo "</div>";

                echo "<div class='contents'>" . $item["content"] . "</div>";
                echo "</div>"; //item
            }
        }

        echo "</div>"; //column_main

    }

    public function startRender()
    {
        parent::startRender();
        echo "<div class='news_view'>";

        $this->renderArchive();
        $this->renderNewsList();

    }

    public function finishRender()
    {
        echo "</div>";//news_view
        parent::finishRender(); // TODO: Change the autogenerated stub
    }
}
